eureka:
   instance:
      preferIpAddress: true
      hostname: localhost
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
